[package]
name = "rust-server"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
zeromq = "0.4.1"
futures = "0.3.31"
tokio = { version = "1", features = ["full"] }
